// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgqOutRkpBuYiOA0-TDr4guy_FYhJ2hws',
    appId: '1:883469593966:web:1787d47a4f5999155ee57f',
    messagingSenderId: '883469593966',
    projectId: 'autobots-67ac0',
    authDomain: 'autobots-67ac0.firebaseapp.com',
    storageBucket: 'autobots-67ac0.appspot.com',
    measurementId: 'G-1EWL182N89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLR7mjtgiSzGtDJ7XNVLOgxGZr14nnM7Q',
    appId: '1:883469593966:android:189a71f0f3f1cbd25ee57f',
    messagingSenderId: '883469593966',
    projectId: 'autobots-67ac0',
    storageBucket: 'autobots-67ac0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVcdskyM33ox_YHssbXaJh-J3KzIsCwXg',
    appId: '1:883469593966:ios:c63a78e06749389b5ee57f',
    messagingSenderId: '883469593966',
    projectId: 'autobots-67ac0',
    storageBucket: 'autobots-67ac0.appspot.com',
    iosBundleId: 'com.example.lsd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVcdskyM33ox_YHssbXaJh-J3KzIsCwXg',
    appId: '1:883469593966:ios:c63a78e06749389b5ee57f',
    messagingSenderId: '883469593966',
    projectId: 'autobots-67ac0',
    storageBucket: 'autobots-67ac0.appspot.com',
    iosBundleId: 'com.example.lsd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgqOutRkpBuYiOA0-TDr4guy_FYhJ2hws',
    appId: '1:883469593966:web:3c16e8261f4a180c5ee57f',
    messagingSenderId: '883469593966',
    projectId: 'autobots-67ac0',
    authDomain: 'autobots-67ac0.firebaseapp.com',
    storageBucket: 'autobots-67ac0.appspot.com',
    measurementId: 'G-WZE253LW9Z',
  );

}